import type { CountryCode } from 'libphonenumber-js/min';

// Static Spanish labels: identical during SSR and browser hydration.
export const phoneCountries: { code: CountryCode; name: string; callingCode: string }[] = [
    {"code":"AR","name":"Argentina","callingCode":"54"},
    {"code":"AF","name":"Afganistán","callingCode":"93"},
    {"code":"AL","name":"Albania","callingCode":"355"},
    {"code":"DE","name":"Alemania","callingCode":"49"},
    {"code":"AD","name":"Andorra","callingCode":"376"},
    {"code":"AO","name":"Angola","callingCode":"244"},
    {"code":"AI","name":"Anguila","callingCode":"1"},
    {"code":"AG","name":"Antigua y Barbuda","callingCode":"1"},
    {"code":"SA","name":"Arabia Saudí","callingCode":"966"},
    {"code":"DZ","name":"Argelia","callingCode":"213"},
    {"code":"AM","name":"Armenia","callingCode":"374"},
    {"code":"AW","name":"Aruba","callingCode":"297"},
    {"code":"AU","name":"Australia","callingCode":"61"},
    {"code":"AT","name":"Austria","callingCode":"43"},
    {"code":"AZ","name":"Azerbaiyán","callingCode":"994"},
    {"code":"BS","name":"Bahamas","callingCode":"1"},
    {"code":"BD","name":"Bangladés","callingCode":"880"},
    {"code":"BB","name":"Barbados","callingCode":"1"},
    {"code":"BH","name":"Baréin","callingCode":"973"},
    {"code":"BE","name":"Bélgica","callingCode":"32"},
    {"code":"BZ","name":"Belice","callingCode":"501"},
    {"code":"BJ","name":"Benín","callingCode":"229"},
    {"code":"BM","name":"Bermudas","callingCode":"1"},
    {"code":"BY","name":"Bielorrusia","callingCode":"375"},
    {"code":"BO","name":"Bolivia","callingCode":"591"},
    {"code":"BA","name":"Bosnia y Herzegovina","callingCode":"387"},
    {"code":"BW","name":"Botsuana","callingCode":"267"},
    {"code":"BR","name":"Brasil","callingCode":"55"},
    {"code":"BN","name":"Brunéi","callingCode":"673"},
    {"code":"BG","name":"Bulgaria","callingCode":"359"},
    {"code":"BF","name":"Burkina Faso","callingCode":"226"},
    {"code":"BI","name":"Burundi","callingCode":"257"},
    {"code":"BT","name":"Bután","callingCode":"975"},
    {"code":"CV","name":"Cabo Verde","callingCode":"238"},
    {"code":"KH","name":"Camboya","callingCode":"855"},
    {"code":"CM","name":"Camerún","callingCode":"237"},
    {"code":"CA","name":"Canadá","callingCode":"1"},
    {"code":"BQ","name":"Caribe neerlandés","callingCode":"599"},
    {"code":"QA","name":"Catar","callingCode":"974"},
    {"code":"TD","name":"Chad","callingCode":"235"},
    {"code":"CZ","name":"Chequia","callingCode":"420"},
    {"code":"CL","name":"Chile","callingCode":"56"},
    {"code":"CN","name":"China","callingCode":"86"},
    {"code":"CY","name":"Chipre","callingCode":"357"},
    {"code":"VA","name":"Ciudad del Vaticano","callingCode":"39"},
    {"code":"CO","name":"Colombia","callingCode":"57"},
    {"code":"KM","name":"Comoras","callingCode":"269"},
    {"code":"CG","name":"Congo","callingCode":"242"},
    {"code":"KP","name":"Corea del Norte","callingCode":"850"},
    {"code":"KR","name":"Corea del Sur","callingCode":"82"},
    {"code":"CR","name":"Costa Rica","callingCode":"506"},
    {"code":"CI","name":"Côte d’Ivoire","callingCode":"225"},
    {"code":"HR","name":"Croacia","callingCode":"385"},
    {"code":"CU","name":"Cuba","callingCode":"53"},
    {"code":"CW","name":"Curazao","callingCode":"599"},
    {"code":"DK","name":"Dinamarca","callingCode":"45"},
    {"code":"DM","name":"Dominica","callingCode":"1"},
    {"code":"EC","name":"Ecuador","callingCode":"593"},
    {"code":"EG","name":"Egipto","callingCode":"20"},
    {"code":"SV","name":"El Salvador","callingCode":"503"},
    {"code":"AE","name":"Emiratos Árabes Unidos","callingCode":"971"},
    {"code":"ER","name":"Eritrea","callingCode":"291"},
    {"code":"SK","name":"Eslovaquia","callingCode":"421"},
    {"code":"SI","name":"Eslovenia","callingCode":"386"},
    {"code":"ES","name":"España","callingCode":"34"},
    {"code":"US","name":"Estados Unidos","callingCode":"1"},
    {"code":"EE","name":"Estonia","callingCode":"372"},
    {"code":"SZ","name":"Esuatini","callingCode":"268"},
    {"code":"ET","name":"Etiopía","callingCode":"251"},
    {"code":"PH","name":"Filipinas","callingCode":"63"},
    {"code":"FI","name":"Finlandia","callingCode":"358"},
    {"code":"FJ","name":"Fiyi","callingCode":"679"},
    {"code":"FR","name":"Francia","callingCode":"33"},
    {"code":"GA","name":"Gabón","callingCode":"241"},
    {"code":"GM","name":"Gambia","callingCode":"220"},
    {"code":"GE","name":"Georgia","callingCode":"995"},
    {"code":"GH","name":"Ghana","callingCode":"233"},
    {"code":"GI","name":"Gibraltar","callingCode":"350"},
    {"code":"GD","name":"Granada","callingCode":"1"},
    {"code":"GR","name":"Grecia","callingCode":"30"},
    {"code":"GL","name":"Groenlandia","callingCode":"299"},
    {"code":"GP","name":"Guadalupe","callingCode":"590"},
    {"code":"GU","name":"Guam","callingCode":"1"},
    {"code":"GT","name":"Guatemala","callingCode":"502"},
    {"code":"GF","name":"Guayana Francesa","callingCode":"594"},
    {"code":"GG","name":"Guernesey","callingCode":"44"},
    {"code":"GN","name":"Guinea","callingCode":"224"},
    {"code":"GQ","name":"Guinea Ecuatorial","callingCode":"240"},
    {"code":"GW","name":"Guinea-Bisáu","callingCode":"245"},
    {"code":"GY","name":"Guyana","callingCode":"592"},
    {"code":"HT","name":"Haití","callingCode":"509"},
    {"code":"HN","name":"Honduras","callingCode":"504"},
    {"code":"HU","name":"Hungría","callingCode":"36"},
    {"code":"IN","name":"India","callingCode":"91"},
    {"code":"ID","name":"Indonesia","callingCode":"62"},
    {"code":"IQ","name":"Irak","callingCode":"964"},
    {"code":"IR","name":"Irán","callingCode":"98"},
    {"code":"IE","name":"Irlanda","callingCode":"353"},
    {"code":"AC","name":"Isla de la Ascensión","callingCode":"247"},
    {"code":"IM","name":"Isla de Man","callingCode":"44"},
    {"code":"CX","name":"Isla de Navidad","callingCode":"61"},
    {"code":"NF","name":"Isla Norfolk","callingCode":"672"},
    {"code":"IS","name":"Islandia","callingCode":"354"},
    {"code":"AX","name":"Islas Aland","callingCode":"358"},
    {"code":"KY","name":"Islas Caimán","callingCode":"1"},
    {"code":"CC","name":"Islas Cocos","callingCode":"61"},
    {"code":"CK","name":"Islas Cook","callingCode":"682"},
    {"code":"FO","name":"Islas Feroe","callingCode":"298"},
    {"code":"FK","name":"Islas Malvinas","callingCode":"500"},
    {"code":"MP","name":"Islas Marianas del Norte","callingCode":"1"},
    {"code":"MH","name":"Islas Marshall","callingCode":"692"},
    {"code":"SB","name":"Islas Salomón","callingCode":"677"},
    {"code":"TC","name":"Islas Turcas y Caicos","callingCode":"1"},
    {"code":"VG","name":"Islas Vírgenes Británicas","callingCode":"1"},
    {"code":"VI","name":"Islas Vírgenes de EE. UU.","callingCode":"1"},
    {"code":"IL","name":"Israel","callingCode":"972"},
    {"code":"IT","name":"Italia","callingCode":"39"},
    {"code":"JM","name":"Jamaica","callingCode":"1"},
    {"code":"JP","name":"Japón","callingCode":"81"},
    {"code":"JE","name":"Jersey","callingCode":"44"},
    {"code":"JO","name":"Jordania","callingCode":"962"},
    {"code":"KZ","name":"Kazajistán","callingCode":"7"},
    {"code":"KE","name":"Kenia","callingCode":"254"},
    {"code":"KG","name":"Kirguistán","callingCode":"996"},
    {"code":"KI","name":"Kiribati","callingCode":"686"},
    {"code":"XK","name":"Kosovo","callingCode":"383"},
    {"code":"KW","name":"Kuwait","callingCode":"965"},
    {"code":"LA","name":"Laos","callingCode":"856"},
    {"code":"LS","name":"Lesoto","callingCode":"266"},
    {"code":"LV","name":"Letonia","callingCode":"371"},
    {"code":"LB","name":"Líbano","callingCode":"961"},
    {"code":"LR","name":"Liberia","callingCode":"231"},
    {"code":"LY","name":"Libia","callingCode":"218"},
    {"code":"LI","name":"Liechtenstein","callingCode":"423"},
    {"code":"LT","name":"Lituania","callingCode":"370"},
    {"code":"LU","name":"Luxemburgo","callingCode":"352"},
    {"code":"MK","name":"Macedonia del Norte","callingCode":"389"},
    {"code":"MG","name":"Madagascar","callingCode":"261"},
    {"code":"MY","name":"Malasia","callingCode":"60"},
    {"code":"MW","name":"Malaui","callingCode":"265"},
    {"code":"MV","name":"Maldivas","callingCode":"960"},
    {"code":"ML","name":"Mali","callingCode":"223"},
    {"code":"MT","name":"Malta","callingCode":"356"},
    {"code":"MA","name":"Marruecos","callingCode":"212"},
    {"code":"MQ","name":"Martinica","callingCode":"596"},
    {"code":"MU","name":"Mauricio","callingCode":"230"},
    {"code":"MR","name":"Mauritania","callingCode":"222"},
    {"code":"YT","name":"Mayotte","callingCode":"262"},
    {"code":"MX","name":"México","callingCode":"52"},
    {"code":"FM","name":"Micronesia","callingCode":"691"},
    {"code":"MD","name":"Moldavia","callingCode":"373"},
    {"code":"MC","name":"Mónaco","callingCode":"377"},
    {"code":"MN","name":"Mongolia","callingCode":"976"},
    {"code":"ME","name":"Montenegro","callingCode":"382"},
    {"code":"MS","name":"Montserrat","callingCode":"1"},
    {"code":"MZ","name":"Mozambique","callingCode":"258"},
    {"code":"MM","name":"Myanmar (Birmania)","callingCode":"95"},
    {"code":"NA","name":"Namibia","callingCode":"264"},
    {"code":"NR","name":"Nauru","callingCode":"674"},
    {"code":"NP","name":"Nepal","callingCode":"977"},
    {"code":"NI","name":"Nicaragua","callingCode":"505"},
    {"code":"NE","name":"Níger","callingCode":"227"},
    {"code":"NG","name":"Nigeria","callingCode":"234"},
    {"code":"NU","name":"Niue","callingCode":"683"},
    {"code":"NO","name":"Noruega","callingCode":"47"},
    {"code":"NC","name":"Nueva Caledonia","callingCode":"687"},
    {"code":"NZ","name":"Nueva Zelanda","callingCode":"64"},
    {"code":"OM","name":"Omán","callingCode":"968"},
    {"code":"NL","name":"Países Bajos","callingCode":"31"},
    {"code":"PK","name":"Pakistán","callingCode":"92"},
    {"code":"PW","name":"Palaos","callingCode":"680"},
    {"code":"PA","name":"Panamá","callingCode":"507"},
    {"code":"PG","name":"Papúa Nueva Guinea","callingCode":"675"},
    {"code":"PY","name":"Paraguay","callingCode":"595"},
    {"code":"PE","name":"Perú","callingCode":"51"},
    {"code":"PF","name":"Polinesia Francesa","callingCode":"689"},
    {"code":"PL","name":"Polonia","callingCode":"48"},
    {"code":"PT","name":"Portugal","callingCode":"351"},
    {"code":"PR","name":"Puerto Rico","callingCode":"1"},
    {"code":"HK","name":"RAE de Hong Kong (China)","callingCode":"852"},
    {"code":"MO","name":"RAE de Macao (China)","callingCode":"853"},
    {"code":"GB","name":"Reino Unido","callingCode":"44"},
    {"code":"CF","name":"República Centroafricana","callingCode":"236"},
    {"code":"CD","name":"República Democrática del Congo","callingCode":"243"},
    {"code":"DO","name":"República Dominicana","callingCode":"1"},
    {"code":"RE","name":"Reunión","callingCode":"262"},
    {"code":"RW","name":"Ruanda","callingCode":"250"},
    {"code":"RO","name":"Rumanía","callingCode":"40"},
    {"code":"RU","name":"Rusia","callingCode":"7"},
    {"code":"EH","name":"Sáhara Occidental","callingCode":"212"},
    {"code":"WS","name":"Samoa","callingCode":"685"},
    {"code":"AS","name":"Samoa Americana","callingCode":"1"},
    {"code":"BL","name":"San Bartolomé","callingCode":"590"},
    {"code":"KN","name":"San Cristóbal y Nieves","callingCode":"1"},
    {"code":"SM","name":"San Marino","callingCode":"378"},
    {"code":"MF","name":"San Martín","callingCode":"590"},
    {"code":"PM","name":"San Pedro y Miquelón","callingCode":"508"},
    {"code":"VC","name":"San Vicente y las Granadinas","callingCode":"1"},
    {"code":"SH","name":"Santa Elena","callingCode":"290"},
    {"code":"LC","name":"Santa Lucía","callingCode":"1"},
    {"code":"ST","name":"Santo Tomé y Príncipe","callingCode":"239"},
    {"code":"SN","name":"Senegal","callingCode":"221"},
    {"code":"RS","name":"Serbia","callingCode":"381"},
    {"code":"SC","name":"Seychelles","callingCode":"248"},
    {"code":"SL","name":"Sierra Leona","callingCode":"232"},
    {"code":"SG","name":"Singapur","callingCode":"65"},
    {"code":"SX","name":"Sint Maarten","callingCode":"1"},
    {"code":"SY","name":"Siria","callingCode":"963"},
    {"code":"SO","name":"Somalia","callingCode":"252"},
    {"code":"LK","name":"Sri Lanka","callingCode":"94"},
    {"code":"ZA","name":"Sudáfrica","callingCode":"27"},
    {"code":"SD","name":"Sudán","callingCode":"249"},
    {"code":"SS","name":"Sudán del Sur","callingCode":"211"},
    {"code":"SE","name":"Suecia","callingCode":"46"},
    {"code":"CH","name":"Suiza","callingCode":"41"},
    {"code":"SR","name":"Surinam","callingCode":"597"},
    {"code":"SJ","name":"Svalbard y Jan Mayen","callingCode":"47"},
    {"code":"TH","name":"Tailandia","callingCode":"66"},
    {"code":"TW","name":"Taiwán","callingCode":"886"},
    {"code":"TZ","name":"Tanzania","callingCode":"255"},
    {"code":"TJ","name":"Tayikistán","callingCode":"992"},
    {"code":"IO","name":"Territorio Británico del Océano Índico","callingCode":"246"},
    {"code":"PS","name":"Territorios Palestinos","callingCode":"970"},
    {"code":"TL","name":"Timor-Leste","callingCode":"670"},
    {"code":"TG","name":"Togo","callingCode":"228"},
    {"code":"TK","name":"Tokelau","callingCode":"690"},
    {"code":"TO","name":"Tonga","callingCode":"676"},
    {"code":"TT","name":"Trinidad y Tobago","callingCode":"1"},
    {"code":"TA","name":"Tristán de Acuña","callingCode":"290"},
    {"code":"TN","name":"Túnez","callingCode":"216"},
    {"code":"TM","name":"Turkmenistán","callingCode":"993"},
    {"code":"TR","name":"Turquía","callingCode":"90"},
    {"code":"TV","name":"Tuvalu","callingCode":"688"},
    {"code":"UA","name":"Ucrania","callingCode":"380"},
    {"code":"UG","name":"Uganda","callingCode":"256"},
    {"code":"UY","name":"Uruguay","callingCode":"598"},
    {"code":"UZ","name":"Uzbekistán","callingCode":"998"},
    {"code":"VU","name":"Vanuatu","callingCode":"678"},
    {"code":"VE","name":"Venezuela","callingCode":"58"},
    {"code":"VN","name":"Vietnam","callingCode":"84"},
    {"code":"WF","name":"Wallis y Futuna","callingCode":"681"},
    {"code":"YE","name":"Yemen","callingCode":"967"},
    {"code":"DJ","name":"Yibuti","callingCode":"253"},
    {"code":"ZM","name":"Zambia","callingCode":"260"},
    {"code":"ZW","name":"Zimbabue","callingCode":"263"},
];
